name: ci
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install redis
        run: sudo apt-get install redis-server
      - name: make test
        run: make test
